# Render Blueprint — CoreBank API
# Deploy via: https://dashboard.render.com/blueprints

services:
  - type: web
    name: corebank-api
    runtime: docker
    plan: free
    repo: https://github.com/MaiHuyHoang592004/corebank-api
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: showcase
      - key: COREBANK_KAFKA_ENABLED
        value: "false"
      - key: JAVA_OPTS
        value: "-Xmx384m"
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: corebank-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: corebank-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: corebank-postgres
          property: password

databases:
  - name: corebank-postgres
    plan: free
    postgresMajorVersion: 16
